
## Standard error of the sample mean

********************************************************************************

The mean of a sample of size $n$ can be used as an estimate of the population mean,

$$ \widehat{\mu} = \bar{X}_n = \frac{\sum_{i=1}^n X_i }{n} $$

The estimated standard error of the the sample mean is usually defined as,

$$ \widehat{Se}\left(\bar{X}_n\right) = \sqrt{\frac{\widehat{\sigma}^2}{n}} = \frac{\widehat{\sigma}}{\sqrt{n}} $$

where $\sigma^2$ is the population variance and $\widehat{\sigma}^2$ is an estimate of the population variance.

********************************************************************************

### Derivation

Firstly, remember that the standard deviation is equal to the square root of the variance,

$$ Se\left(\bar{X}_n\right) = \sqrt{Var\left(\bar{X}_n\right)} $$

Now substitute the definition of $\bar{X}_n$ given above,

$$ \sqrt{Var\left(\bar{X}_n\right)} = \sqrt{Var\left( \frac{\sum_{i=1}^n X_i }{n} \right)} $$

Using the rule $Var(aX) = a^2Var(X)$, we can rearrange it,

$$ \sqrt{Var\left( \frac{\sum_{i=1}^n X_i }{n} \right)} = \sqrt{\frac{1}{n^2}Var\left({\sum_{i=1}^n X_i}\right)} $$

Assuming the sample values are independent, we can use the rule $Var(\sum X_i) = \sum Var(X_i)$, to rearrange it again,

$$ \sqrt{\frac{1}{n^2}Var\left({\sum_{i=1}^n X_i}\right)} = \sqrt{\frac{1}{n^2}\sum_{i=1}^nVar\left(X_i\right)} $$

Assuming the sample values all have the same variance, $\sigma^2$, this becomes,

$$ \sqrt{\frac{1}{n^2}\sum_{i=1}^nVar\left(X_i\right)} = \sqrt{\frac{1}{n^2}\sum_{i=1}^n\sigma^2} = \sqrt{\frac{1}{n^2} n\sigma^2} $$

Cancelling out some of the $n$'s to give,

$$ Se\left(\bar{X}_n\right) = \sqrt{\frac{\sigma^2}{n}} $$

Finally, we replace $\sigma^2$ with an estimate, $\widehat{\sigma}^2$, to obtain an estimate of $Se\left(\bar{X}_n\right)$,

$$ \widehat{Se}\left(\bar{X}_n\right) = \sqrt{\frac{\widehat{\sigma}^2}{n}} $$

And if we really want to, we can also re-express it as,

$$ \sqrt{\frac{\widehat{\sigma}^2}{n}} = \frac{\sqrt{\widehat{\sigma}^2}}{\sqrt{n}} = \frac{\widehat{\sigma}}{\sqrt{n}} $$

Furthermore, since $Var\left(\bar{X}_n\right) = \left[Se\left(\bar{X}_n\right)\right]^2 = \sigma^2/n$, this also implies that,

$$ \widehat{Var}\left(\bar{X}_n\right) = \frac{\widehat{\sigma}^2}{n} $$


********************************************************************************
