
## Variance

********************************************************************************

$\mbox{Var}\left[ aX \right] = a^2\mbox{Var}\left[ X \right]$

********************************************************************************

#### Variance as an expected value

$\mbox{Var}\left[ X \right] = \mbox{E}\left[ \left( X - \mbox{E}\left[ X \right] \right)^2 \right] = \mbox{E}\left[ X^2 \right] - \left(\mbox{E}\left[ X \right] \right)^2$

Another form that is sometimes useful (e.g. in calculating the expected value of the <a href="Binomial distribution.html">binomial distribution</a>) is,

$\mbox{Var}\left[ X \right] = \mbox{E}\left[ X(X-1) \right] + \mbox{E}\left[ X \right] - \left(\mbox{E}\left[ X \right] \right)^2$

********************************************************************************

#### Variance of a linear combination of random variables

$\mbox{Var}\left[ aX + bY \right] = a^2\mbox{Var}\left[ X \right] + b^2\mbox{Var}\left[ Y \right] + 2ab \mbox{Cov}\left[ X,Y \right]$

$\mbox{Var}\left[ \sum_{i=1}^N a_i X_i \right] = \sum_{i=1}^N a_i^2\mbox{Var}\left[ X_i \right] + 2\sum_{i}^N\sum_{j>i}^N a_i a_j \mbox{Cov}\left[ X_i,X_j \right]$

********************************************************************************

#### Variance of a product of independent variables

$\mbox{Var}\left[ XY \right] = \left(\mbox{E}\left[ X \right] \right)^2 \mbox{Var}\left[ Y \right] + \left(\mbox{E}\left[ Y \right] \right)^2 \mbox{Var}\left[ X \right] + \mbox{Var}\left[ X \right]\mbox{Var}\left[ Y \right]$

which can be simplfied to,

$\mbox{Var}\left[ XY \right] = \mbox{E}\left[ X^2 \right] \mbox{E}\left[ Y^2 \right] - \left(\mbox{E}\left[ X \right] \right)^2 \left(\mbox{E}\left[ Y \right] \right)^2$

********************************************************************************
