---
title: Generalized additive models (GAMs)
output: 
    html_document:
        code_folding: hide
        css: '../notes/resources/style.css'
        toc: true
        toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r default_setup, include=FALSE, code=readLines("../notes/resources/knitr_setup.R")}
```

```{r bespoke_setup, include=FALSE}
knitr::opts_chunk$set(
  fig.align = "default",
  fig.asp = 1,
  fig.width = 5,
  out.width = "50%"
)
```

********************************************************************************

## Example data

```{r}
library(tidyverse)

set.seed(42)
n <- 1000
x <- seq(0, 3, length = n)
Ey <- (sin(3 * x) + 2 * sin(2 * x^2) + 3 * sin(x^3)) / exp(x)
y <- rnorm(n, mean = Ey, sd = 0.2)

mar <- c(2, 2, 2, 2)
xlim<-c(0,3)
ylim <- c(-1.75, 2.5)
cex <- 0.5

par(mar = mar)
plot(x, y, pch = 19, col = "grey", xlim = xlim, ylim = ylim, cex = cex)
lines(x, Ey, lwd = 2)
```

********************************************************************************

## Polynomials

### Basis functions

```{r}
for(degree in c(5, 10)) {
  X = poly(x, degree, raw = TRUE)
  plot(x, y, type = "n", xlim = xlim, ylim = ylim,
       main = paste0("Polynomial basis functions: degree ", degree))
  abline(h = 1, lwd = 2)
  for(i in 1:ncol(X)) lines(x, X[,i], col=i+1, lwd=2)
}
```

### Fitted models

```{r}
for(degree in c(5, 10, 50, 200)){
  X = poly(x, degree, raw = TRUE)
  model = lm(y ~ X)
  plot(x, y, type = "n", ylim = ylim, 
       main = paste("Polynomial fitted model: degree", degree))
  points(x, y, pch = 19, col = "grey", cex = cex)
  lines(x, fitted(model), col = "blue", lwd = 2)
  legend("topright", paste("AIC =", signif(AIC(model), 3)))
}
```

********************************************************************************

## Truncated power series

### Basis functions

```{r}
for (degree in c(1, 3)) {
  n_knots <- 12
  df <- n_knots + 1
  knots <- seq(0, 3, length = df)[1:n_knots]
  X <- 1:n_knots %>% 
    map_dfc(function(k){
      if_else(x < knots[k], 0, (x - knots[k])^degree)
    }) %>% 
    as.matrix
  plot(x, y, type = "n", ylim = ylim, 
       main = paste0(main = "TPS basis functions: degree ", degree, ", knots ", n_knots))
  for (k in 1:n_knots) {
    lines(x[X[, k] != 0], X[X[, k] != 0, k], col = k + 1)
  }
  abline(h = 1)
  abline(v = knots, lty = 2, col = "grey")
}
```

### Fitted models

```{r}
for (n_knots in c(12, 24)) {
  for (degree in c(1, 3)) {
    df <- n_knots + 1
    knots <- seq(0, 3, length = df)[1:n_knots]
    X <- 1:n_knots %>% 
      map_dfc(function(k){
        if_else(x < knots[k], 0, (x - knots[k])^degree)
      }) %>% 
      as.matrix
    model <- lm(y ~ X)
    plot(x, y, type = "n", ylim = ylim, 
         main = paste0(main = "TPS fitted model: degree ", degree, ", knots ", n_knots))
    points(x, y, pch = 19, col = "grey", cex = cex)
    lines(x, fitted(model), col = "blue", lwd = 2)
    legend("topright", paste("AIC =", signif(AIC(model), 3)))
  }
}
```

********************************************************************************

## B-splines

### Basis functions

```{r}
make_knots = function(degree, n_knots_internal) {
  knots <- seq(0, 3, length = n_knots_internal + 2)
  knots[-c(1, length(knots))]
}
make_X = function(degree, knots) {
  df <- length(knots) + degree + 1
  X = splines::bs(x = x, knots = knots, degree = degree, intercept = TRUE)
  as.matrix(X)
}
plot_X = function(X, knots = NULL, main = "") {
  plot(x, y, type = "n", ylim = ylim, 
       main = paste0(main = "B-spline basis functions: degree ", degree, ", internal knots ", length(knots)))
  for (k in 1:ncol(X)){
    lines(x[X[, k] != 0], X[X[, k] != 0, k], col = k + 1)
  }
  if (!is.null(knots)) {
    abline(v = c(0, knots, 3), lty = 2, col = "grey")
  }  
}
for(n_knots_internal in 11){
  for(degree in c(1, 3)){
    knots <- make_knots(degree, n_knots_internal)
    X <- make_X(degree, knots)
    plot_X(X, knots, main = "")
  }
}
```

### Fitted models

```{r}
for(n_knots_internal in 11){
  for(degree in c(1, 3)){
    knots <- make_knots(degree, n_knots_internal)
    X <- make_X(degree, knots)
    model = lm(y ~ X)
    plot_X(X, knots, main = "")
    lines()
  }
}
```

```{r, eval=FALSE, echo=FALSE}
library(fda)
library(splines)

# Degree-1 b-spline with 11 equally spaced internal knots
d <- 1
n_knots_internal <- 11
knots <- seq(0, 3, length = n_knots_internal + 2)[-c(1, n_knots_internal + 2)]
knots
df <- length(knots) + d + 1
df
# X <- eval.basis(x, create.bspline.basis(rangeval=c(0,3), nbasis=df, norder=d+1)) ; dim(X)
X <- splines::bs(x = x, knots = knots, degree = d, intercept = T)
lm.bs.d1.k11eq <- lm(y ~ -1 + X)
# unscaled basis functions
plot(x, y, type = "n", ylim = ylim)
for (k in 1:df) lines(x[X[, k] != 0], X[X[, k] != 0, k], col = k + 1)
abline(v = c(0, knots, 3), lty = 2, col = "grey")


# scaled basis functions
png("gam_artificial_bs_d1_k11eq_basisfunctions_scaled.png", height = height, width = width, bg = bg, res = res)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
for (k in 1:df) lines(x[X[, k] != 0], X[X[, k] != 0, k] * coef(lm.bs.d1.k11eq)[k], col = k + 1)
abline(v = c(0, knots, 3), lty = 2, col = "grey")
dev.off()
# fitted model
png("gam_artificial_bs_d1_k11eq_fitted.png", height = height, width = width, bg = bg, res = res)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
points(x, y, pch = 19, col = "grey", cex = cex)
lines(x, fitted(lm.bs.d1.k11eq), col = "blue", lwd = 2)
abline(v = c(0, knots, 3), lty = 2, col = "grey")
legend("topright", paste("AIC =", signif(AIC(lm.bs.d1.k11eq), 3)), bg = "white")
dev.off()


# Degree-3 b-spline with 11 equally spaced internal knots
d <- 3
n_knots_internal <- 11
knots <- seq(0, 3, length = n_knots_internal + 2)[-c(1, n_knots_internal + 2)]
knots
df <- length(knots) + d + 1
df
# X <- eval.basis(x, create.bspline.basis(rangeval=c(0,3), nbasis=df, norder=d+1)) ; dim(X)
X <- bs(x = x, knots = knots, degree = d, intercept = T)
dim(X)
lm.bs.d3.k11eq <- lm(y ~ -1 + X)
# unscaled basis functions
png("gam_artificial_bs_d3_k11eq_basisfunctions.png", height = height, width = width, bg = bg, res = res)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
for (k in 1:df) lines(x[X[, k] != 0], X[X[, k] != 0, k], col = k + 1)
abline(v = c(0, knots, 3), lty = 2, col = "grey")
dev.off()
# scaled basis functions
png("gam_artificial_bs_d3_k11eq_basisfunctions_scaled.png", height = height, width = width, bg = bg, res = res)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
for (k in 1:df) lines(x[X[, k] != 0], X[X[, k] != 0, k] * coef(lm.bs.d3.k11eq)[k], col = k + 1)
abline(v = c(0, knots, 3), lty = 2, col = "grey")
dev.off()
# fitted model
png("gam_artificial_bs_d3_k11eq_fitted.png", height = height, width = width, bg = bg, res = res)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
points(x, y, pch = 19, col = "grey", cex = cex)
lines(x, fitted(lm.bs.d3.k11eq), col = "blue", lwd = 2)
abline(v = c(0, knots, 3), lty = 2, col = "grey")
legend("topright", paste("AIC =", signif(AIC(lm.bs.d3.k11eq), 3)), bg = "white")
dev.off()

# Degree-3 b-spline 11 unequally spaced knots
do.this <- F
if (do.this == T) {
  d <- 3
  n_knots_internal <- 11
  knots <- list()
  aic <- numeric(0)
  knots[[1]] <- best.knots
  #  knots[[1]] <- c(seq(0,1.6,0.5)[-1], seq(2,2.2,0.2), seq(2.5,2.8,0.1)) ; knots[[1]] ; length(knots[[1]])
  X <- bs(x = x, knots = knots[[1]], degree = d, intercept = F)
  dim(X)
  aic[1] <- AIC(lm(y ~ -1 + X))
  for (i in 2:10000) {
    knots[[i]] <- jitter(knots[[i - 1]])
    knots[[i]] <- ifelse(knots[[i]] < 0, 0.1, knots[[i]])
    knots[[i]] <- ifelse(knots[[i]] > 3, 2.9, knots[[i]])
    knots[[i]] <- sort(knots[[i]])
    X <- bs(x = x, knots = knots[[i]], degree = d, intercept = F)
    aic[i] <- AIC(lm(y ~ -1 + X))
    if (aic[i] > aic[i - 1]) knots[[i]] <- knots[[i - 1]]
    cat("i = ", i, ", min(AIC)=", min(aic), "\n", sep = "")
  }
  best.knots <- knots[[which.min(aic)]]
  X <- bs(x = x, knots = best.knots, degree = d, intercept = F)
  dim(X)
  test.model <- lm(y ~ -1 + X)
  par(mfrow = c(1, 1), mar = mar)
  plot(x, y, type = "n", ylim = ylim)
  points(x, y, pch = 19, col = "grey", cex = cex)
  lines(x, fitted(test.model), col = "blue", lwd = 2)
  abline(v = c(0, best.knots, 3), lty = 2, col = "grey")
  legend("topright", paste("AIC =", signif(AIC(test.model), 3)), bg = "white")
  n - test.model$df.residual
}

# Degree-3 b-spline 11 unequally spaced knots
knots <- c(
  0.07458434, 0.53498073, 1.19775010, 1.72283298, 1.97116144, 2.24407186,
  2.44662816, 2.50024478, 2.68491558, 2.68542864, 2.87134377
)
knots
# n_knots_internal <- length(knots)
df <- length(knots) + d + 1
df
X <- bs(x = x, knots = knots, degree = d, intercept = F)
dim(X)
lm.bs.d3.k11uneq <- lm(y ~ -1 + X)
summary(lm.bs.d3.k11uneq)
length(fitted(lm.bs.d3.k11uneq))
AIC(lm.bs.d3.k11uneq)
png("gam_artificial_bs_d3_k11uneq_fitted.png", height = height, width = width, bg = bg, res = res)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
points(x, y, pch = 19, col = "grey", cex = cex)
lines(x, fitted(lm.bs.d3.k11uneq), col = "blue", lwd = 2)
abline(v = c(0, knots, 3), lty = 2, col = "grey")
legend("topright", paste("AIC =", signif(AIC(lm.bs.d3.k11uneq), 3)), bg = "white")
dev.off()
```

********************************************************************************

## Cubic splines

### Basis functions

```{r}
```

### Fitted models

```{r}
```

```{r, eval=FALSE, echo=FALSE}
library(mgcv)

png("gam_artificial_cs_dfdefault_fitted.png", height = height, width = width, bg = bg, res = res)
cubic.default <- read.csv("cubic_default.csv", header = T)
head(cubic.default)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
points(x, y, pch = 19, col = "grey", cex = cex)
lines(x, cubic.default$P_y, lwd = 2, col = "blue")
dev.off()

png("gam_artificial_cs_df100_fitted.png", height = height, width = width, bg = bg, res = res)
cubic.100 <- read.csv("cubic_100.csv", header = T)
head(cubic.100)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
points(x, y, pch = 19, col = "grey", cex = cex)
lines(x, cubic.100$P_y, lwd = 2, col = "blue")
dev.off()

png("gam_artificial_cs_gcv_fitted.png", height = height, width = width, bg = bg, res = res)
cubic.gcv <- read.csv("cubic_gcv.csv", header = T)
head(cubic.gcv)
par(mfrow = c(1, 1), mar = mar)
plot(x, y, type = "n", ylim = ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
points(x, y, pch = 19, col = "grey", cex = cex)
lines(x, cubic.gcv$P_y, lwd = 2, col = "blue")
dev.off()



##################################################################################################################################################################
##################################################################################################################################################################

# WIGGLINESS MEASURE

##################################################################################################################################################################
##################################################################################################################################################################

height2 <- 350
width2 <- 800
S <- seq(0, 2 * pi, length = 1000)
png("wiggliness_0.png", height = height2, width = width2, bg = bg, res = res)
par(mfrow = c(1, 2), mar = mar)
Ylim <- c(-1.5, 1.5)
plot(x, y, type = "n", ylim = Ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
curve(sin(4 * x) + 0.1 * sin(25 * x), add = T)

plot(x, y, type = "n", ylim = Ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
curve(sin(4 * x), add = T)
dev.off()

png("wiggliness_1.png", height = height2, width = width2, bg = bg, res = res)
par(mfrow = c(1, 2), mar = mar)
Ylim <- c(-8, 8)
plot(x, y, type = "n", ylim = Ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
curve(eval(D(expression(sin(4 * x) + 0.1 * sin(25 * x)), "x")), add = T)

plot(x, y, type = "n", ylim = Ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
curve(eval(D(expression(sin(4 * x)), "x")), add = T)
dev.off()

png("wiggliness_2.png", height = height2, width = width2, bg = bg, res = res)
par(mfrow = c(1, 2), mar = mar)
Ylim <- c(-80, 80)
plot(x, y, type = "n", ylim = Ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
curve(eval(D(D(expression(sin(4 * x) + 0.1 * sin(25 * x)), "x"), "x")), add = T)

plot(x, y, type = "n", ylim = Ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
curve(eval(D(D(expression(sin(4 * x)), "x"), "x")), add = T)
dev.off()

png("wiggliness_3.png", height = height2, width = width2, bg = bg, res = res)
par(mfrow = c(1, 2), mar = mar)
Ylim <- c(0, 7000)
plot(x, y, type = "n", ylim = Ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
dydx2 <- function(x) eval(D(D(expression(sin(4 * x) + 0.1 * sin(25 * x)), "x"), "x"))^2
lines(S, dydx2(S))
polygon(S, dydx2(S), col = "grey")
area <- integrate(dydx2, lower = 0, upper = 2 * pi)$value
legend("topleft", paste("area=", round(area)))

plot(x, y, type = "n", ylim = Ylim)
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
  density = NULL, angle = 45,
  col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
)
dydx2 <- function(x) eval(D(D(expression(sin(4 * x)), "x"), "x"))^2
lines(S, dydx2(S))
polygon(c(0, S, 3), c(0, dydx2(S), 0), col = "grey")
area <- integrate(dydx2, lower = 0, upper = 2 * pi)$value
legend("topleft", paste("area=", round(area)))
dev.off()
```

********************************************************************************

## Bias vs Variance

```{r, eval=FALSE, echo=FALSE}



# save.image("Gam figures.RData")


# windows()
# par(mfrow=c(2,2))
# X <- matrix(NA, nrow=n, ncol=K)
# for(k in 1:K) X[,k] <- ifelse(x<knots[k],0,(x-knots[k])^d)
# X <- cbind(rep(1,n), X)

# plot(x,Y, type="n", main=paste("Basis functions: Truncated Power Series\n(d =", d,", df =",df,")",sep=""), ylab="Y")
# abline(v=knots, lty=2, col="grey")
# matplot(x, X, add=T, type="l", lty=1, lwd=2)
# for(i in 1:df){
#  index <- which(X[,i]>0)
#  lines(x[index],X[index,i],col=i, lwd=2)
# }

# model <- lm(Y~ -1 + basis.functions)
# plot(x,Y, type="n", main=paste("Scaled basis functions: Truncated PS\n( degree =",Degree,", df =",DF,")"), ylab="Y")
# for(i in 1:DF){
#  index <- which(basis.functions[,i]*model$coef[i]!=0)
#  lines(x[index],(basis.functions[,i]*model$coef[i])[index],col=i, lwd=2)
# }
# abline(v=c(0,knots,3), lty=2, col="grey")

# plot(x,Y, col="grey", pch=19, cex=Cex, main=paste("Fitted smooth: Truncated PS\n( power =", Power,", df =",DF,")"), ylab="Y")
# abline(v=knots, lty=2, col="grey")
# lines(x,fitted(model), col="blue", lwd=2)
# legend('topright', paste("AIC =",signif(AIC(model),3)), bg="white")

# Power <- 3 ; DF <- length(knots)+1
# basis.functions <- matrix(NA, nrow=length(x), ncol=length(knots))
# for(i in 1:length(knots)){
#  bf <- x-knots[i]
#  bf <- ifelse(bf<0,0,bf)
#  basis.functions[,i] <- bf^Power
# }
# basis.functions <- cbind(rep(1,length(Y)),basis.functions)
# plot(x,Y, type="n", main=paste("Basis functions: Truncated PS\n( power =", Power,", df =",DF,")"), ylab="Y")
# abline(v=knots, lty=2, col="grey")
# for(i in 1:DF){
#  index <- which(basis.functions[,i]>0)
#  lines(x[index],basis.functions[,i][index],col=i, lwd=2)
# }
# model <- lm(Y~ -1 + basis.functions)
# plot(x,Y, type="n", main=paste("Scaled basis functions: Truncated PS\n( degree =",Degree,", df =",DF,")"), ylab="Y")
# for(i in 1:DF){
#  index <- which(basis.functions[,i]*model$coef[i]!=0)
#  lines(x[index],(basis.functions[,i]*model$coef[i])[index],col=i, lwd=2)
# }
# abline(v=c(0,knots,3), lty=2, col="grey")
# plot(x,Y, col="grey", pch=19, cex=Cex, main=paste("Fitted smooth: Truncated PS\n( power =", Power,", df =",DF,")"), ylab="Y")
# abline(v=knots, lty=2, col="grey")
# lines(x,fitted(model), col="blue", lwd=2)
# legend('topright', paste("AIC =",signif(AIC(model),3)), bg="white")



##################################################################################################################################################################
##################################################################################################################################################################

# B-SPLINES

##################################################################################################################################################################
##################################################################################################################################################################




# windows()
# library(fda)
# par(mfrow=c(2,2))

# knots <- seq(0,3,length=13)
# knots <- knots[-c(1,length(knots))]

# Degree <- 1 ; DF <- length(knots)+Degree+1
# basis <- create.bspline.basis(rangeval=c(0,3), nbasis=DF, norder=Degree+1)
# basis.functions <- eval.basis(x,basis)
# plot(x,Y, type="n", main=paste("Basis functions: b-spline\n( degree =",Degree,", df =",DF,")"), ylab="Y")
# abline(v=c(0,knots,3), lty=2, col="grey")
# for(i in 1:DF){
#  index <- which(basis.functions[,i]!=0)
#  lines(x[index],basis.functions[,i][index],col=i, lwd=2)
# }
# model <- lm(Y ~ -1 + basis.functions)
# plot(x,Y, type="n", main=paste("Scaled basis functions: b-spline\n( degree =",Degree,", df =",DF,")"), ylab="Y")
# for(i in 1:DF){
#  index <- which(basis.functions[,i]*model$coef[i]!=0)
#  lines(x[index],(basis.functions[,i]*model$coef[i])[index],col=i, lwd=2)
# }
# abline(v=c(0,knots,3), lty=2, col="grey")
# plot(x,Y, col="grey", pch=19, cex=Cex, main=paste("Fitted smooth: b-spline\n( degree =",Degree,", df =",DF,")"))
# abline(v=c(0,knots,3), lty=2, col="grey")
# lines(x,as.numeric(fitted(model)), col="blue", lwd=2)
# legend('topright', paste("AIC =",signif(AIC(model),3)), bg="white")

# Degree <- 3 ; DF <- length(knots)+Degree+1
# basis <- create.bspline.basis(rangeval=c(0,3), nbasis=DF, norder=Degree+1)
# basis.functions <- eval.basis(x,basis)
# plot(x,Y, type="n", main=paste("Basis functions: b-spline\n( degree =",Degree,", df =",DF,")"), ylab="Y")
# abline(v=c(0,knots,3), lty=2, col="grey")
# for(i in 1:DF){
#  index <- which(basis.functions[,i]!=0)
#  lines(x[index],basis.functions[,i][index],col=i, lwd=2)
# }
# model <- lm(Y ~ -1 + basis.functions)
# plot(x,Y, type="n", main=paste("Scaled basis functions: b-spline\n( degree =",Degree,", df =",DF,")"), ylab="Y")
# for(i in 1:DF){
#  index <- which(basis.functions[,i]*model$coef[i]!=0)
#  lines(x[index],(basis.functions[,i]*model$coef[i])[index],col=i, lwd=2)
# }
# abline(v=c(0,knots,3), lty=2, col="grey")
# plot(x,Y, col="grey", pch=19, cex=Cex, main=paste("Fitted smooth: b-spline\n( degree =",Degree,", df =",DF,")"))
# abline(v=c(0,knots,3), lty=2, col="grey")
# lines(x,as.numeric(fitted(model)), col="blue", lwd=2)
# legend('topright', paste("AIC =",signif(AIC(model),3)), bg="white")


# B-SPLINES 3 - irregularly spaced knots ------------------------------------------------------------------------


# source("C:\\Users\\darren\\Documents\\STATISTICS\\PhD\\Bayes project\\salsa func.txt")
# landmarks <- salsa.func(x=(x/max(x)), y=Y, maxknots=10, degree=Degree)
# landmarks[,1]

# knots <- max(x)*c(0.4374374, 0.4924925, 0.5705706, 0.6716717, 0.7427427, 0.8138138, 0.8798799, 0.8818819)
# Degree <- 3 ; DF <- length(knots)+Degree+1

# length(knots)
# basis <- create.bspline.basis(rangeval=c(0,3), nbasis=length(knots)+Degree+1, norder=4, breaks=c(0,knots,3))
# basis.functions <- eval.basis(x,basis)

# windows()
# par(mfrow=c(1,2))
# plot(x,Y, type="n", main=paste("Basis functions: b-spline\n( degree =",Degree,", df =",DF,")"), ylab="Y")
# abline(v=c(0,knots,3), lty=2, col="grey")
# for(i in 1:(length(knots)+Degree+1)){
#  index <- which(basis.functions[,i]>0)
#  lines(x[index],basis.functions[,i][index],col=i, lwd=2)
# }
# model <- lm(Y ~ -1 + basis.functions)
# plot(x,Y, type="n", main=paste("Scaled basis functions: b-spline\n( degree =",Degree,", df =",DF,")"), ylab="Y")
# for(i in 1:DF){
#  index <- which(basis.functions[,i]*model$coef[i]!=0)
#  lines(x[index],(basis.functions[,i]*model$coef[i])[index],col=i, lwd=2)
# }
# abline(v=c(0,knots,3), lty=2, col="grey")
# plot(x,Y, col="grey", pch=19, cex=Cex, main=paste("Fitted smooth: b-spline\n( degree =",Degree,", df =",DF,")"))
# abline(v=c(0,knots,3), lty=2, col="grey")
# lines(x,as.numeric(fitted(model)), col="blue", lwd=2)
# legend('topright', paste("AIC =",signif(AIC(model),3)), bg="white")



##################################################################################################################################################################
##################################################################################################################################################################

# CUBIC SPLINES

##################################################################################################################################################################
##################################################################################################################################################################



# windows()
# par(mfrow=c(2,4))
# x <- seq(0,4*pi,length=1000)
# A <- sin(x)
# B <- 0.5*sin(x)
# d1A <- cos(x)
# d1B <- 0.5*cos(x)
# d2A <- -sin(x)
# d2B <- 0.5*-sin(x)

# plot(x,A, type="l", main="Function A", ylim=c(-1.2,1.2), ylab="y")
# abline(h=0, lty=2, col="grey")
# plot(x,d1A, type="l", main="Function A: 1st derivative", ylim=c(-1.2,1.2), ylab="y")
# abline(h=0, lty=2, col="grey")
# plot(x,d2A, type="l", main="Function A: 2nd derivative", ylim=c(-1.2,1.2), ylab="y")
# abline(h=0, lty=2, col="grey")
# plot(x,d2A^2, type="l", main="Function A: 2nd derivative^2", ylim=c(-1.2,1.2), ylab="y")
# p#olygon(x,d2A^2, col="lightgrey")

# plot(x,B, type="l", main="Function B", ylim=c(-1.2,1.2), ylab="y")
# abline(h=0, lty=2, col="grey")
# plot(x,d1B, type="l", main="Function B: 1st derivative", ylim=c(-1.2,1.2), ylab="y")
# abline(h=0, lty=2, col="grey")
# plot(x,d2B, type="l", main="Function B: 2nd derivative", ylim=c(-1.2,1.2), ylab="y")
# abline(h=0, lty=2, col="grey")
# p##lot(x,d2B^2, type="l", main="Function B: 2nd derivative^2", ylim=c(-1.2,1.2), ylab="y")
# p#olygon(x,d2B^2, col="lightgrey")


# BIAS vs VARIANCE ------------------------------------------------------------------------

do.this <- F
if (do.this == T) {
  # Example: B-splines

  sims <- 1000
  d <- 3
  sigma.temp <- 1

  png("gam_artificial_bias_variance1.png", height = height, width = width, bg = bg, res = res)
  n_knots_internal <- 5
  knots <- seq(0, 3, length = n_knots_internal + 2)[-c(1, n_knots_internal + 2)]
  knots
  df <- length(knots) + d + 1
  df
  X <- bs(x = x, knots = knots, degree = d, intercept = T)
  dim(X)
  par(mfrow = c(1, 1), mar = mar)
  plot(x, y, type = "n", ylim = ylim)
  rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
    density = NULL, angle = 45,
    col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
  )
  predictions <- matrix(NA, ncol = sims, nrow = n)
  for (sim in 1:sims) { # i<-1
    new.y <- rnorm(n, Ey, sigma.temp)
    model <- lm(new.y ~ -1 + X)
    predictions[, sim] <- fitted(model)
    lines(x, predictions[, sim], col = "grey")
  }
  lines(x, Ey, lwd = 2)
  lines(x, rowMeans(predictions), col = "blue", lty = 2, lwd = 2)
  abline(v = c(0, knots, 3), lty = 2, col = "grey")
  dev.off()

  png("gam_artificial_bias_variance2.png", height = height, width = width, bg = bg, res = res)
  n_knots_internal <- 50
  knots <- seq(0, 3, length = n_knots_internal + 2)[-c(1, n_knots_internal + 2)]
  knots
  df <- length(knots) + d + 1
  df
  X <- bs(x = x, knots = knots, degree = d, intercept = T)
  dim(X)
  par(mfrow = c(1, 1), mar = mar)
  plot(x, y, type = "n", ylim = ylim)
  rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
    density = NULL, angle = 45,
    col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
  )
  predictions <- matrix(NA, ncol = sims, nrow = n)
  for (sim in 1:sims) { # i<-1
    new.y <- rnorm(n, Ey, sigma.temp)
    model <- lm(new.y ~ -1 + X)
    predictions[, sim] <- fitted(model)
    lines(x, predictions[, sim], col = "grey")
  }
  lines(x, Ey, lwd = 2)
  lines(x, rowMeans(predictions), col = "blue", lty = 2, lwd = 2)
  abline(v = c(0, knots, 3), lty = 2, col = "grey")
  dev.off()

  png("gam_artificial_bias_variance3.png", height = height, width = width, bg = bg, res = res)
  knots <- c(
    0.07458434, 0.53498073, 1.19775010, 1.72283298, 1.97116144, 2.24407186,
    2.44662816, 2.50024478, 2.68491558, 2.68542864, 2.87134377
  )
  knots
  df <- length(knots) + d + 1
  df
  X <- bs(x = x, knots = knots, degree = d, intercept = T)
  dim(X)
  par(mfrow = c(1, 1), mar = mar)
  plot(x, y, type = "n", ylim = ylim)
  rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4],
    density = NULL, angle = 45,
    col = "white", border = NULL, lty = par("lty"), lwd = par("lwd")
  )
  predictions <- matrix(NA, ncol = sims, nrow = n)
  for (sim in 1:sims) { # i<-1
    new.y <- rnorm(n, Ey, sigma.temp)
    model <- lm(new.y ~ -1 + X)
    predictions[, sim] <- fitted(model)
    lines(x, predictions[, sim], col = "grey")
  }
  lines(x, Ey, lwd = 2)
  lines(x, rowMeans(predictions), col = "blue", lty = 2, lwd = 2)
  abline(v = c(0, knots, 3), lty = 2, col = "grey")
  dev.off()
} # end of 'do.this'



# do.this <- F ; if(do.this==T){
# library(fda)
# x <- seq(0,3,length=1000)
# y <- (sin(3*x)+2*sin(2*x^2)+3*sin(x^3))/exp(x)
# Y <- y + rnorm(length(y),0,0.5)
# Degree <- 3  ; sims <- 1000
# windows()
# par(mfrow=c(1,2))

# DF <- 10
# knots <- seq(0,3,length=(DF-Degree-1))
# knots <- knots[-c(1,length(knots))]
# plot(x, Y, type="n", ylim=c(-2.5,3.5), main=paste("Degree",Degree,"B-spline with",DF,"parameters"))
# abline(v=c(0,knots,3), lty=2, col="lightgrey")
# results <- matrix(NA, nrow=length(x), ncol=sims)
# for(i in 1:sims){
#  Y <- y + rnorm(length(y),0,2)
#  basis <- create.bspline.basis(rangeval=c(0,3), nbasis=length(knots)+Degree+1, norder=Degree+1)
#  basis.functions <- eval.basis(x,basis)
#  model <- lm(Y ~ basis.functions)
#  results[,i] <- as.numeric(fitted(model))
#  lines(x,as.numeric(fitted(model)), col="lightgrey", lwd=2)
# }
# lines(x,y,lwd=2)
# lines(x,apply(results,1,mean),lwd=2, lty=2, col="blue")

# DF <- 50
# knots <- seq(0,3,length=(DF-Degree-1))
# knots <- knots[-c(1,length(knots))]
# plot(x, Y, type="n", ylim=c(-2.5,3.5), main=paste("Degree",Degree,"B-spline with",DF,"parameters"))
# abline(v=c(0,knots,3), lty=2, col="lightgrey")
# results <- matrix(NA, nrow=length(x), ncol=sims)
# for(i in 1:sims){
#  Y <- y + rnorm(length(y),0,2)
#  basis <- create.bspline.basis(rangeval=c(0,3), nbasis=length(knots)+Degree+1, norder=Degree+1)
#  basis.functions <- eval.basis(x,basis)
#  model <- lm(Y ~ basis.functions)
#  results[,i] <- as.numeric(fitted(model))
#  lines(x,as.numeric(fitted(model)), col="lightgrey", lwd=2)
# }
# lines(x,y,lwd=2)
# lines(x,apply(results,1,mean),lwd=2, lty=2, col="blue")
# }



```
